# Generated by Django 4.2.23 on 2025-10-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinica',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='clinica',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='clinica',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Clinica',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
