# Generated by Django 5.2.3 on 2025-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data do Exame')),
                ('forca', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Força (N)')),
            ],
        ),
    ]
