# Generated by Django 4.2.23 on 2025-10-23 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_clinica_cidade_remove_paciente_clinica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='mao_dominante',
            field=models.CharField(choices=[('destro', 'Destro'), ('ambidestro', 'Ambidestro'), ('canhoto', 'Canhoto')], default='destro', max_length=10),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
