# Generated by Django 4.2.23 on 2025-10-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paciente_mao_dominante_alter_administrador_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='matricula',
        ),
    ]
