# Generated by Django 4.2.25 on 2025-10-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_administrador_usuario_exame'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exame',
            new_name='Teste',
        ),
    ]
