# Generated by Django 4.2.23 on 2025-10-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_profissional_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='nome',
            field=models.CharField(default='sem cpf cadastrado', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariobase',
            name='senha',
            field=models.CharField(default='123', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuariobase',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
