# Generated by Django 4.2.25 on 2025-10-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_exame_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='teste',
            name='detalhes',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='teste',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='teste',
            name='forca',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teste',
            name='tempo',
            field=models.IntegerField(),
        ),
    ]
