# Generated by Django 5.1.1 on 2024-10-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_pacient"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pacient",
            new_name="Patient",
        ),
    ]
