# Generated by Django 4.2.23 on 2025-10-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_administrador_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariobase',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
