# Generated by Django 4.2.25 on 2025-10-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teste_detalhes_alter_teste_data_alter_teste_forca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teste',
            old_name='usuario',
            new_name='paciente',
        ),
    ]
