# Generated by Django 5.1.2 on 2024-10-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_pacient_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="cpf",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
