# Generated by Django 4.2.25 on 2025-10-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_teste_paciente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teste',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='testes', to='core.paciente'),
        ),
    ]
