# Generated by Django 4.2.23 on 2025-10-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_administrador_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissionais', to='core.paciente'),
        ),
    ]
