# Generated by Django 4.2.23 on 2025-10-30 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profissional_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='paciente',
        ),
        migrations.CreateModel(
            name='ProfissionalPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profissional')),
            ],
            options={
                'verbose_name': 'Relacionamento Profissional-Paciente',
                'unique_together': {('profissional', 'paciente')},
            },
        ),
        migrations.AddField(
            model_name='profissional',
            name='paciente',
            field=models.ManyToManyField(blank=True, related_name='profissionais', through='core.ProfissionalPaciente', to='core.paciente'),
        ),
    ]
