# Generated by Django 4.2.23 on 2025-10-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_profissional_paciente_profissionalpaciente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissionalpaciente',
            options={'verbose_name': 'Relacionamento Profissional-Paciente', 'verbose_name_plural': 'Relacionamentos Profissional-Paciente'},
        ),
    ]
