# Generated by Django 4.2.23 on 2025-10-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_profissionalpaciente_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='data_nascimento',
        ),
    ]
