# Generated by Django 4.2.23 on 2025-10-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_profissional_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='paciente',
            new_name='pacientes',
        ),
    ]
