# Generated by Django 4.2.23 on 2025-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_paciente_profissional_pacientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionalpaciente',
            name='data_atendimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
