# Generated by Django 4.2.23 on 2025-10-31 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_profissionalpaciente_data_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionalpaciente',
            name='data_atendimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
