# Generated by Django 4.2.23 on 2025-10-31 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('core', '0017_alter_profissionalpaciente_data_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='perfil',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
