# Generated by Django 4.2.26 on 2025-12-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_teste_paciente'),
        ('core', '0018_paciente_perfil'),
    ]

    operations = [
    ]
