# Generated by Django 4.2.26 on 2025-12-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_merge_0008_alter_teste_paciente_0018_paciente_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariobase',
            name='senha',
        ),
    ]
